# Homebrew formula for the prebuilt `datapress` CLI.
#
# Generated by packaging/homebrew/update-formula.sh — do not edit by hand.
# Installs the standalone binary (both DuckDB + DataFusion backends bundled)
# from the GitHub release; it does NOT compile from source.
class Datapress < Formula
  desc "Fast multi-backend (DuckDB / DataFusion) HTTP server over Parquet and Delta"
  homepage "https://datap-rs.org"
  version "0.8.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "3c71f0507973beaa2f2fad2c536e38957f2d73c89eab9974affe1080201f3865"
    end
    on_intel do
      odie "datapress has no prebuilt Intel macOS binary. Install with: cargo install datapress"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "01a028a3ce4b60b12c30c2aee0a67d4dfb45df68addd931ca24895c64c48e80d"
    end
    on_intel do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "f7d60c027fda01ec0164e7888de22702201381807afb329e4893f01a352bda1b"
    end
  end

  def install
    bin.install "datapress"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/datapress --version")
  end
end
