# Homebrew formula for the prebuilt `datapress` CLI.
#
# Generated by packaging/homebrew/update-formula.sh — do not edit by hand.
# Installs the standalone binary (both DuckDB + DataFusion backends bundled)
# from the GitHub release; it does NOT compile from source.
class Datapress < Formula
  desc "Fast multi-backend (DuckDB / DataFusion) HTTP server over Parquet and Delta"
  homepage "https://datap-rs.org"
  version "0.6.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "8e52249ad2fa1894952f9f6ad1b1b9f285ad525552dade13cd1029f052c93aae"
    end
    on_intel do
      odie "datapress has no prebuilt Intel macOS binary. Install with: cargo install datapress"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "05130b0eac0b10734304ddcfc5f673b0887ef93feecb4adc1c693076124e72eb"
    end
    on_intel do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "a5bafce41b0922cd1f8d445a6fddd57bf965b92de3a6b53ef5886be48ce79c99"
    end
  end

  def install
    bin.install "datapress"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/datapress --version")
  end
end
