# Homebrew formula for the prebuilt `datapress` CLI.
#
# Generated by packaging/homebrew/update-formula.sh — do not edit by hand.
# Installs the standalone binary (both DuckDB + DataFusion backends bundled)
# from the GitHub release; it does NOT compile from source.
class Datapress < Formula
  desc "Fast multi-backend (DuckDB / DataFusion) HTTP server over Parquet and Delta"
  homepage "https://datap-rs.org"
  version "0.5.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "e0c13c69b60a94458a7c6dbf479307fd2564fd39d8681e72b02e9e040dcc2deb"
    end
    on_intel do
      odie "datapress has no prebuilt Intel macOS binary. Install with: cargo install datapress"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "0687488c3ecab67fd38d493e58969018b08e75dae306cdcebcb02881192b3bf9"
    end
    on_intel do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "fd24ff0721ab1882109d80dee79b1017fba7dce4e0a6cdea3d93823b3763f086"
    end
  end

  def install
    bin.install "datapress"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/datapress --version")
  end
end
